---
# tasks file for ansible-azure-data-studio

## Install Dependencies
- name: Install a list of packages
  apt:
    pkg:
    - libxss1
    - libgconf-2-4
    - libunwind8

- name: Install a .deb package from the internet.
  apt:
    deb: https://sqlopsbuilds.azureedge.net/stable/4970733324ef8254b7c22a5dc55af7f8a1dea93f/azuredatastudio-linux-1.48.0.deb
