---
# tasks file for ansible-azure-data-studio

## Install Dependencies
- name: Install a list of packages
  apt:
    pkg:
    - libxss1
    - libgconf-2-4
    - libunwind8

- name: Install a .deb package from the internet.
  apt:
    deb: https://sqlopsbuilds.azureedge.net/stable/4095037f2578c23033867e611e82c13de114ca5a/azuredatastudio-linux-1.19.0.deb
